services:
  # Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

      # Rate Service
  rate-service:
      build: ./rateService
      ports:
          - ${RATE_PORT}:${RATE_PORT}
      environment:
            SPRING_APPLICATION_NAME: rate-service
            SERVER_PORT: ${RATE_PORT}

            # Database
            SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
            SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
            SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

            # ExchangeRate API config
            EXCHANGE_API_BASE_URL: https://v6.exchangerate-api.com/v6
            EXCHANGE_API_KEY: ${EXCHANGE_API_KEY}

            # Security config
            SECURITY_API_KEY: ${SECURITY_API_KEY}
            SECURITY_API_SECRET: ${SECURITY_API_SECRET}
            SECURITY_API_ENABLED: true

            # Logging
            LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: DEBUG
            LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_HTTP: TRACE
            LOGGING_LEVEL_COM_RATE_SERVICE: DEBUG

            # CORS
            CORS_ALLOWED_ORIGINS: "*"
            CORS_ALLOWED_METHODS: GET,POST,PUT,DELETE
            CORS_ALLOWED_HEADERS: "*"

            # API Key settings
            API_KEY_HEADER: ${API_KEY_HEADER}
            API_KEY_CACHE_ENABLED: true
            API_KEY_CACHE_DURATION: 5m

            # Actuator
            MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: true

      depends_on:
            postgres:
              condition: service_healthy
      healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8081/api/v1/rate/status"]
            interval: 30s
            timeout: 10s
            retries: 3

  # Main Service
  main-service:
    build: ./mainService
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: ${MAIN_PORT}
      SPRING_APPLICATION_NAME: mainService


      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      RATE_SERVICE_URL: ${RATE_SERVICE_URL}
      SECURITY_API_KEY: ${SECURITY_API_KEY}
      SECURITY_API_SECRET: ${SECURITY_API_SECRET}
      SECURITY_API_ENABLED: true
      APP_API_KEY: ${APP_API_KEY}
      APP_API_SECRET: ${APP_API_SECRET}


    #      # Logging
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: DEBUG
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_HTTP: TRACE
      LOGGING_LEVEL_COM_RATE_SERVICE: DEBUG

      CORS_ALLOWED_ORIGINS: "*"
      CORS_ALLOWED_METHODS: GET,POST,PUT,DELETE
      CORS_ALLOWED_HEADERS: "*"


      API_KEY_HEADER: ${API_KEY_HEADER}
      API_KEY_CACHE_ENABLED: true
      API_KEY_CACHE_DURATION: 5m


    depends_on:
      rate-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/status"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pgdata:
