-- public."conversion" definition

-- Drop table

-- DROP TABLE public."conversion";

CREATE TABLE public."conversion" (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	amount numeric(38, 2) NULL,
	from_currency varchar(255) NULL,
	rate numeric(38, 2) NULL,
	"result" numeric(38, 2) NULL,
	"timestamp" timestamp(6) NULL,
	to_currency varchar(255) NULL,
	CONSTRAINT conversion_pkey PRIMARY KEY (id)
);