spring.application.name=mainService
server.port=8080
server.address=localhost

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=Ak0881216
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Security (for incoming client requests)
app.api.key=SJDLKSKHJGFYAY76QO99912IAJilkkyfrtyy&&&&&vfklddlkhsghhj
app.api.secret=345678jvfdfkjknbfgui6890khjgfdddsfvnnmlkjhjgf

# Rate Service Communication (must match rate-service's security keys)
rate.service.api.key=SJDLKSKHJGFYAY76QO99912IAJilkkyfrtyy&&&&&vfklddlkhsghhj
rate.service.api.secret=345678jvfdfkjknbfgui6890khjgfdddsfvnnmlkjhjgf
rate-service.url=http://rate-service:8081/api/v1/rate

# Actuator
management.endpoints.web.exposure.include=health,metrics,prometheus

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http=TRACE
logging.level.com.main_service=DEBUG
