spring.application.name=mainService

logging.level.org.springframework.web= DEBUG

server.port=8080
#spring.profiles.active=local
#spring.datasource.url=jdbc:postgresql://db:5432/converter
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=Ak0881216
management.endpoints.web.exposure.include=health,metrics,prometheus
logging.level.org.springframework.http=TRACE
#
#security.api.key=${security.api.key}
#security.api.secret=${securiity.api.secret}


#security.api.key=SJDLKSKHJGFYAY76QO99912IAJilkkyfrtyy&&&&&vfklddlkhsghhjhhfhjhkffhkllkkvkkjkkkjfkyrjjgccvlkxfdfghjkjs
#security.api.secret=345678jvfdfkjknbfgui6890khjgfdddsfvnnmlkjhjgfthhfytr45579uhylkkyfr
security.api.key=SJDLKSKHJGFYAY76QO99912IAJilkkyfrtyy&&&&&vfklddlkhsghhj
security.api.secret=345678jvfdfkjknbfgui6890khjgfdddsfvnnmlkjhjgf
security.api.token.expiration=3600


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

#Docker internal network
rate-service.url=http://rate-service:8081/api/v1/rate
